# GPT-2 Debug Configuration (Tiny model for testing)

model:
  vocab_size: 1000  # Tiny vocab

  # Weight initialization
  weight_init:
    std: 0.02
    residual_pattern: 'c_proj.weight'
    position_init_std: 0.02

  # Token embeddings
  token_embedding:
    embedding_dim: 64  # Tiny dim
    init_std: 0.02

  # Position embeddings (GPT-2 uses learned position embeddings)
  position_embedding:
    max_position_embeddings: 128
    embedding_dim: 64
    init_std: 0.02

  # Transformer backbone
  transformer:
    hidden_dim: 64
    n_layers: 2  # Just 2 layers
    block_size: 128
    dropout: 0.0
    bias: true

    # Layer normalization
    normalization:
      norm_eps: 0.00001  # 1e-5
      bias: true

    # Multi-head attention
    attention:
      num_heads: 4
      bias: true
      max_seq_length: 128
      is_causal: true
      use_flash_attention: false

    # Feed-forward network
    ffn:
      intermediate_dim: 256  # 4 * hidden_dim
      activation: gelu
      bias: true

  # Output head
  output_head:
    tie_word_embeddings: true
    lm_head_bias: false

# Training configuration
training:
  # Top-level training loop fields
  token_budget: 2560  # 10 steps × 2 batch × 128 seq_len
  max_iters: 10  # Safety limit for debugging
  log_interval: 1
  seed: 1337
  gradient_accumulation_steps: 1
  precision: fp32

  # Data configuration
  data:
    dataset: debug
    data_dir: ./data/debug
    num_workers: 1
    pin_memory: false

  # Batch configuration
  batch:
    batch_size: 2
    sequence_length: 128

  # Optimizer configuration
  optimizer:
    optimizer_type: adamw
    learning_rate: 0.0006
    weight_decay: 0.1
    beta1: 0.9
    beta2: 0.95
    grad_clip: 1.0
    eps: 0.00000001
    parameter_grouping: dimension

  # Learning rate schedule
  lr_schedule:
    schedule_type: cosine
    warmup_iters: 2
    lr_decay_iters: 10
    min_lr: 0.00006

  # Loss configuration
  loss:
    cross_entropy_weight: 1.0

  # Evaluation configuration
  evaluation:
    eval_interval: 5
    eval_iters: 2
    num_eval_batches: 50

  # Checkpointing configuration
  checkpoint:
    save_dir: ./checkpoints/debug/gpt2
    save_interval: 10
    save_best: false
    keep_last_n: 1

  # Torch compilation configuration
  torch_compilation:
    compile: false

  # Execution configuration
  execution:
    strategy: fsdp
    fsdp:
      sharding_strategy: FULL_SHARD
      wrapping_strategy: BY_BLOCK  # Wrap each transformer block
      precision: PURE  # Use pure precision (no mixed precision)
      use_orig_params: true  # Needed for torch.compile compatibility

  # Weights & Biases logging
  wandb_logging:
    enabled: false
    project: minllm-debug
    entity: null  # Set your W&B entity/username
    group: null
    name: debug-gpt2
    tags: ["debug", "gpt2", "test"]
    log_artifacts: false
    rank_zero_only: true
    log_interval: 1
